version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
        environment:
          PGHOST: 127.0.0.1
          PGUSER: map-it
          RAILS_ENV: test
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: map-it
          POSTGRES_DB: map-it-test
          POSTGRES_PASSWORD: ""

    steps:
      - checkout

      # Restore bundle cache
      - type: cache-restore
        name: Restore bundle cache
        keys:
          - v2-dependencies-{{ checksum "Gemfile.lock" }}
          - v2-dependencies-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache
      - type: cache-save
        name: Store bundle cache
        key: v2-dependencies-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      # Run rspec in parallel
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out test_results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)


      # Save test results for timing analysis
      - store_test_results:
          path: test_results
